### ISSUE TITLE
Api connection error

### ISSUE THREAD

**Issue by Tim-VL** [FriendsOfShopware/FroshPlatformBunnycdnMediaStorage#41] opened 2023-01-16 21:31 UTC
### PHP Version

8.1

### Shopware Version

6.4.18

### Actual behaviour

When the plugin is anabled, I get many error in the Notifications.
Please also see https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1672588561377459

![afbeelding](https://user-images.githubusercontent.com/75847795/212768513-90ca77dc-b9c2-4880-b6fe-d8867a00d116.png)

### Expected behaviour

normal functioning / no error

### Steps to Reproduce?

add theme and config theme
install bunnycdn plugin and config
enable filesystem on CDN
afbeelding

**Comment by tinect** [comment] 2023-01-17 21:01
Hi,
I've transferred the issue to the correct repository.

Does it help to compile theme and install assets in cli?

**Comment by Tim-VL** [comment] 2023-01-18 09:55
Hi @tinect,

For the theme Yes. But I still get api errors.
FYI; Theme compiling took almost one hour.

**Comment by tinect** [comment] 2023-01-19 18:44
>FYI; Theme compiling took almost one hour.
Please read the hint marked with the blue bubble and the questions mark at the setting. This is no issue by this plugin, just for the count of data being transferred.

I cannot reproduce your problem with the error. It's thrown by shopware when you got logged out in background f.e.
But this seems unrelated to this plugin? 🤔

**Comment by Tim-VL** [comment] 2023-01-21 19:43
I'll have an look again on Monday, perhaps its something else.

**Comment by tinect** [comment] 2023-01-30 11:35
If this is still relevant for you, feel free to come back with more details.

**Closed by tinect** 2023-01-30 11:35 UTC
Labels: kind/bug
